### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [MarcMcArthur/McSplurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by MarcMcArthur** [comment]
I've added the mobile meta tag in the header. Not sure I can see any difference.

**Comment by kenmazaika** [comment]
Thumbs up.  Looks perfect.  If you open the app on a mobile phone it will look much better (after you deploy to heroku).  Keep up the good work coding! :+1:
